name: CI

on:
  push:
    branches:
      - master
      - upcoming
      - mono-region
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install binutils
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3

      - name: Install poryscript
        run: |
          wget https://github.com/huderlem/poryscript/releases/download/3.6.0/poryscript-linux.zip
          unzip poryscript-linux.zip
          mkdir -p tools/poryscript
          mv poryscript-linux/poryscript tools/poryscript/poryscript
          mv poryscript-linux/*.json tools/poryscript/
          chmod +x tools/poryscript/poryscript

      - name: ROM
        run: make -j$(nproc) -O all

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: pokeemerald-mono-region
          path: pokeemerald.gba
